spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 574898903244-qrjp11vrbl3dh7alaneqman8odgao4fb.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
#              - openid
#          facebook:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug